# -*- coding: utf-8 -*-
"""calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ISxFjG2UIEZQQSPVSg3Z8ZpwxOdpAeB
"""

def add(x,y):
    return(x+y)
def substract(x,y):
    return(x-y)
def multiply(x,y):
    return(x*y)

